import {useEffect,useState} from 'react';
import {BrowserRouter,Routes,Route,Link,Navigate,useNavigate,useParams} from 'react-router-dom';
import {supabase,api} from './supabase';
const LV=s=>s>=80?'#ff4d4d':s>=60?'#ff9f43':s>=30?'#f5d547':'#3ee6b5';
function useSession(){const[s,setS]=useState(undefined);useEffect(()=>{supabase.auth.getSession().then(({data})=>setS(data.session));const{data}=supabase.auth.onAuthStateChange((_e,x)=>setS(x));return()=>data.subscription.unsubscribe()},[]);return s}
function Guard({s,children}){if(s===undefined)return<p className="w mu">Loading…</p>;return s?children:<Navigate to="/login" replace/>}
function Nav({s}){return<nav><div className="w"><b>TrustHire AI</b><Link to="/">Home</Link><Link to="/analyze">Analyze</Link><Link to="/safety">Safety</Link><Link to="/reports">Community</Link>{s?<><Link to="/history">History</Link><button className="btn g" onClick={()=>supabase.auth.signOut()}>Logout</button></>:<Link to="/login">Login</Link>}</div></nav>}
function Landing(){return<div className="w"><h1>Verify Before You Apply.</h1><p className="mu">AI-assisted, explainable protection against fake jobs and internship scams.</p><Link className="btn" to="/analyze">Check an Opportunity</Link> <Link className="btn g" to="/safety">Safety Guide</Link>
<div className="grid" style={{marginTop:24}}>{['Paste details','Rule-based + AI analysis','Read the evidence','Verify independently'].map((t,i)=><div className="card" key={t}><b>{i+1}. {t}</b></div>)}</div><p className="mu">Advisory only. Report fraud: <a href="https://cybercrime.gov.in/">cybercrime.gov.in</a> · helpline 1930.</p></div>}
function Auth({s}){const[m,setM]=useState('login'),[e,setE]=useState(''),[p,setP]=useState(''),[msg,setMsg]=useState(''),[busy,setB]=useState(false);
 if(s)return<Navigate to="/history" replace/>;
 const go=async()=>{setMsg('');if(!e||(m!=='reset'&&p.length<8))return setMsg('Enter a valid email and a password of 8+ characters');setB(true);
  const r=m==='reset'?await supabase.auth.resetPasswordForEmail(e,{redirectTo:location.origin+'/login'}):m==='signup'?await supabase.auth.signUp({email:e,password:p}):await supabase.auth.signInWithPassword({email:e,password:p});
  setB(false);setMsg(r.error?r.error.message:m==='reset'?'Reset email sent if the account exists.':m==='signup'?'Check your email to confirm, then log in.':'')};
 return<div className="w"><h1>{m==='signup'?'Create account':m==='reset'?'Reset password':'Login'}</h1><div className="card"><input placeholder="Email" value={e} onChange={x=>setE(x.target.value)}/>{m!=='reset'&&<input type="password" placeholder="Password" value={p} onChange={x=>setP(x.target.value)}/>}<button className="btn" disabled={busy} onClick={go}>{busy?'Please wait…':'Continue'}</button><p className="err">{msg}</p>
 <p className="mu"><a href="#" onClick={x=>{x.preventDefault();setM('login')}}>Login</a> · <a href="#" onClick={x=>{x.preventDefault();setM('signup')}}>Sign up</a> · <a href="#" onClick={x=>{x.preventDefault();setM('reset')}}>Forgot password</a></p></div></div>}
const F=[['company_name','Company name *'],['role','Job / internship title'],['url','Opportunity URL'],['company_website','Official company website'],['recruiter_name','Recruiter name'],['recruiter_email','Recruiter email'],['recruiter_phone','Recruiter phone'],['salary','Salary / stipend'],['location','Location']];
function Result({r}){const[sv,setSv]=useState(false);return<div className="card"><h2 style={{color:LV(r.risk_score)}}>{r.risk_score}/100 — {r.risk_level}</h2><p className="mu">{r.summary} Method: <b>{r.method}</b>{r.demo&&' · DEMO (not stored)'}</p>
{r.ai_summary&&<p>AI second opinion: {r.ai_summary}</p>}
{r.indicators.map((i,k)=><div key={k} className="card tag"><b>{i.title}</b> <span className="mu">({i.severity}, +{i.weight})</span><br/><i className="mu">Evidence: “{i.evidence}”</i><br/>{i.explanation}<br/><b>Next step:</b> {i.recommendation}</div>)}
{r.positives.map((p,k)=><div key={k} className="card pos">✓ <b>{p.title}</b> — {p.explanation}</div>)}
<p className="mu">{r.limitations||''} Advisory only; cannot confirm an offer is genuine or fraudulent.</p>{r.id&&<button className="btn g" disabled={sv} onClick={async()=>{await api('/api/saved',{method:'POST',body:{analysisId:r.id}});setSv(true)}}>{sv?'Saved':'Save'}</button>} <button className="btn g" onClick={()=>window.print()}>Print / PDF</button></div>}
function Analyze({s}){const[f,setF]=useState({opportunity_type:'Job'}),[r,setR]=useState(null),[err,setErr]=useState(''),[busy,setB]=useState(false);
 const go=async()=>{setErr('');setR(null);setB(true);try{setR(await api(s?'/api/analyze':'/api/demo/analyze',{method:'POST',body:f}))}catch(x){setErr(x.message)}setB(false)};
 return<div className="w"><h1>Analyze an opportunity</h1>{!s&&<p className="mu">Not logged in: results are not saved. <Link to="/login">Create an account</Link> for history.</p>}<div className="card">
 {F.map(([k,l])=><label key={k}>{l}<input maxLength={300} onChange={x=>setF({...f,[k]:x.target.value})}/></label>)}
 <select onChange={x=>setF({...f,opportunity_type:x.target.value})}>{['Job','Internship','Freelance','Work From Home','Other'].map(o=><option key={o}>{o}</option>)}</select>
 <textarea rows={5} placeholder="Job description" onChange={x=>setF({...f,description:x.target.value})}/><textarea rows={3} placeholder="Recruiter message" onChange={x=>setF({...f,recruiter_message:x.target.value})}/>
 <p className="mu">Never paste passwords, OTPs, PINs or card numbers.</p><button className="btn" disabled={busy} onClick={go}>{busy?'Analyzing…':'Analyze with TrustHire AI'}</button><p className="err">{err}</p></div>{r&&<Result r={r}/>}</div>}
function History(){const[d,setD]=useState(null),[q,setQ]=useState(''),[lv,setLv]=useState(''),[err,setErr]=useState('');const load=()=>api('/api/analyses').then(setD).catch(x=>setErr(x.message));useEffect(()=>{load()},[]);
 if(err)return<p className="w err">{err}</p>;if(!d)return<p className="w mu">Loading…</p>;
 const c=l=>d.filter(a=>a.risk_level===l).length,rows=d.filter(a=>(!q||a.opportunities?.company_name.toLowerCase().includes(q.toLowerCase()))&&(!lv||a.risk_level===lv));
 return<div className="w"><h1>Dashboard</h1><div className="grid"><div className="card">Total<h2>{d.length}</h2></div><div className="card">Low<h2>{c('LOW RISK')}</h2></div><div className="card">Flagged (high/critical)<h2>{c('HIGH RISK')+c('CRITICAL RISK')}</h2></div></div>
 {d.length?<><div className="card">{['LOW RISK','MODERATE RISK','HIGH RISK','CRITICAL RISK'].map(l=><div key={l}>{l} ({c(l)})<div className="bar"><i style={{width:c(l)/d.length*100+'%'}}/></div></div>)}</div>
 <input placeholder="Search company" onChange={x=>setQ(x.target.value)}/><select onChange={x=>setLv(x.target.value)}><option value="">All levels</option>{['LOW RISK','MODERATE RISK','HIGH RISK','CRITICAL RISK'].map(l=><option key={l}>{l}</option>)}</select>
 {rows.map(a=><div className="card" key={a.id}><b>{a.opportunities?.company_name}</b> — {a.opportunities?.role||a.opportunities?.opportunity_type}<br/><span style={{color:LV(a.risk_score)}}>{a.risk_score} · {a.risk_level}</span> <span className="mu">{new Date(a.created_at).toLocaleString()}</span><br/><Link className="btn g" to={'/analysis/'+a.id}>View</Link> <button className="btn g" onClick={async()=>{if(confirm('Delete?')){await api('/api/analyses/'+a.id,{method:'DELETE'});load()}}}>Delete</button></div>)}</>
 :<div className="card"><h3>Analyze your first opportunity.</h3><Link className="btn" to="/analyze">Analyze</Link></div>}</div>}
function Detail(){const{id}=useParams(),[r,setR]=useState(null),[e,setE]=useState('');useEffect(()=>{api('/api/analyses/'+id).then(a=>setR({...a,id:a.id})).catch(x=>setE(x.message))},[id]);
 return<div className="w">{e?<p className="err">{e}</p>:r?<Result r={r}/>:<p className="mu">Loading…</p>}</div>}
function Safety(){const[q,setQ]=useState(''),[a,setA]=useState(''),[b,setB]=useState(false);
 return<div className="w"><h1>Safety Hub</h1><div className="grid">{[['Never pay to get hired','Legitimate employers generally do not charge applicants.'],['Never share','OTPs, PINs, passwords, card details.'],['Verify','Find the company site yourself; match recruiter email to its domain.'],['If you paid','Stop contact, keep evidence, tell your bank, report it.']].map(([t,d])=><div className="card" key={t}><b>{t}</b><p className="mu">{d}</p></div>)}</div>
 <p>Official resources (not TrustHire services): <a href="https://cybercrime.gov.in/">National Cyber Crime Reporting Portal</a> · helpline <b>1930</b>.</p>
 <h2>TrustHire Assistant</h2><div className="card"><textarea rows={3} maxLength={1000} placeholder="Ask about a scam or message" onChange={x=>setQ(x.target.value)}/><button className="btn" disabled={b} onClick={async()=>{setB(true);try{const r=await api('/api/assistant',{method:'POST',body:{question:q}});setA(r.answer+' ['+r.method+']')}catch(x){setA(x.message)}setB(false)}}>{b?'Thinking…':'Ask'}</button><p>{a}</p><p className="mu">Risk guidance only. It cannot verify companies.</p></div></div>}
function Reports({s}){const[d,setD]=useState(null),[f,setF]=useState({}),[m,setM]=useState('');const load=q=>api('/api/reports'+(q?'?q='+encodeURIComponent(q):'')).then(setD).catch(x=>setM(x.message));useEffect(()=>{load()},[]);
 return<div className="w"><h1>Community reports</h1><p className="mu">{d?.disclaimer||'Unverified reports'}</p><input placeholder="Search company" onChange={x=>load(x.target.value)}/>{d?.reports.map(r=><div className="card" key={r.id}><b>{r.company_name}</b> {r.title}<br/>{r.description}</div>)}{d&&!d.reports.length&&<p className="mu">No approved reports yet.</p>}
 {s?<div className="card"><h3>Submit a report</h3><input placeholder="Company / recruiter" onChange={x=>setF({...f,company_name:x.target.value})}/><input placeholder="Title" onChange={x=>setF({...f,title:x.target.value})}/><textarea placeholder="What happened? (no phone numbers or emails)" onChange={x=>setF({...f,description:x.target.value})}/><button className="btn" onClick={async()=>{try{const r=await api('/api/reports',{method:'POST',body:f});setM(r.note)}catch(x){setM(x.message)}}}>Submit for moderation</button></div>:<p><Link to="/login">Login</Link> to submit a report.</p>}<p className="err">{m}</p></div>}
export default function App(){const s=useSession();return<BrowserRouter><Nav s={s}/><Routes><Route path="/" element={<Landing/>}/><Route path="/login" element={<Auth s={s}/>}/><Route path="/analyze" element={<Analyze s={s}/>}/><Route path="/safety" element={<Safety/>}/><Route path="/reports" element={<Reports s={s}/>}/><Route path="/history" element={<Guard s={s}><History/></Guard>}/><Route path="/analysis/:id" element={<Guard s={s}><Detail/></Guard>}/><Route path="*" element={<Navigate to="/"/>}/></Routes></BrowserRouter>}
