import 'dotenv/config';
import express from 'express';import cors from 'cors';import helmet from 'helmet';import rateLimit from 'express-rate-limit';
import {createClient} from '@supabase/supabase-js';
import {analyze,validate} from './engine.js';import {assistant,aiSummary} from './assistant.js';
const {SUPABASE_URL,SUPABASE_ANON_KEY,FRONTEND_ORIGIN='http://localhost:5173',PORT=4000}=process.env;
const app=express();app.use(helmet());app.use(cors({origin:FRONTEND_ORIGIN}));app.use(express.json({limit:'50kb'}));
app.use('/api',rateLimit({windowMs:60000,max:60}));
const client=t=>createClient(SUPABASE_URL,SUPABASE_ANON_KEY,{global:{headers:t?{Authorization:'Bearer '+t}:{}},auth:{persistSession:false}});
// Identity comes from the verified JWT; the user-scoped client means Postgres RLS enforces isolation.
const auth=async(req,res,next)=>{const t=(req.headers.authorization||'').replace(/^Bearer /,'');if(!t)return res.status(401).json({error:'Login required'});
 const db=client(t),{data,error}=await db.auth.getUser(t);if(error||!data.user)return res.status(401).json({error:'Invalid session'});req.user=data.user;req.db=db;next()};
const w=f=>(q,s)=>f(q,s).catch(e=>{console.error(e.message);s.status(500).json({error:'Server error'})});
const bad=(s,m)=>s.status(400).json({error:m});
app.get('/api/health',(q,s)=>s.json({ok:true}));
app.post('/api/demo/analyze',w(async(q,s)=>{const v=validate(q.body);if(v.errors.length)return bad(s,v.errors.join('; '));s.json({...analyze(v.value),demo:true})}));
app.post('/api/analyze',auth,w(async(q,s)=>{const v=validate(q.body);if(v.errors.length)return bad(s,v.errors.join('; '));
 const r=analyze(v.value),ai=await aiSummary(v.value,r);if(ai)r.method='hybrid';
 const o=await q.db.from('opportunities').insert({...v.value,user_id:q.user.id}).select('id').single();if(o.error)throw o.error;
 const a=await q.db.from('analyses').insert({opportunity_id:o.data.id,user_id:q.user.id,risk_score:r.risk_score,risk_level:r.risk_level,method:r.method,summary:r.summary,indicators:r.indicators,positives:r.positives,ai_summary:ai}).select('id').single();if(a.error)throw a.error;
 s.status(201).json({id:a.data.id,...r,ai_summary:ai})}));
app.get('/api/analyses',auth,w(async(q,s)=>{const{data,error}=await q.db.from('analyses').select('id,risk_score,risk_level,created_at,opportunities(company_name,role,opportunity_type)').order('created_at',{ascending:false}).limit(200);if(error)throw error;s.json(data)}));
app.get('/api/analyses/:id',auth,w(async(q,s)=>{const{data,error}=await q.db.from('analyses').select('*,opportunities(*)').eq('id',q.params.id).maybeSingle();if(error)throw error;data?s.json(data):s.status(404).json({error:'Not found'})}));
app.delete('/api/analyses/:id',auth,w(async(q,s)=>{const a=await q.db.from('analyses').select('opportunity_id').eq('id',q.params.id).maybeSingle();if(!a.data)return s.status(404).json({error:'Not found'});const{error}=await q.db.from('opportunities').delete().eq('id',a.data.opportunity_id);if(error)throw error;s.status(204).end()}));
app.get('/api/saved',auth,w(async(q,s)=>{const{data,error}=await q.db.from('saved_opportunities').select('analysis_id,notes,created_at');if(error)throw error;s.json(data)}));
app.post('/api/saved',auth,w(async(q,s)=>{const{error}=await q.db.from('saved_opportunities').upsert({user_id:q.user.id,analysis_id:q.body.analysisId,notes:String(q.body.notes||'').slice(0,500)},{onConflict:'user_id,analysis_id'});if(error)return bad(s,'Could not save');s.status(201).json({ok:true})}));
app.delete('/api/saved/:id',auth,w(async(q,s)=>{const{error}=await q.db.from('saved_opportunities').delete().eq('analysis_id',q.params.id);if(error)throw error;s.status(204).end()}));
app.get('/api/profile',auth,w(async(q,s)=>{const{data,error}=await q.db.from('profiles').select('*').maybeSingle();if(error)throw error;s.json(data||{})}));
app.put('/api/profile',auth,w(async(q,s)=>{const f=k=>String(q.body[k]??'').trim().slice(0,100);const{error}=await q.db.from('profiles').upsert({id:q.user.id,name:f('name'),preferred_role:f('preferred_role'),education:f('education'),location:f('location')});if(error)throw error;s.json({ok:true})}));
const scrub=t=>String(t||'').replace(/\+?\d[\d\s-]{8,}\d/g,'[phone removed]').replace(/[^\s@]+@[^\s@]+\.[^\s@]+/g,'[email removed]');
app.post('/api/reports',auth,w(async(q,s)=>{const b=q.body||{};if(!b.company_name||!b.description)return bad(s,'Company and description are required');
 const{error}=await q.db.from('community_reports').insert({user_id:q.user.id,company_name:scrub(b.company_name).slice(0,120),title:scrub(b.title).slice(0,120),description:scrub(b.description).slice(0,1500),source_url:String(b.source_url||'').slice(0,300),report_date:b.report_date||null});if(error)return bad(s,'Could not submit');s.status(201).json({ok:true,note:'Submitted for moderation. Community reports are unverified.'})}));
app.get('/api/reports',w(async(q,s)=>{let r=client().from('community_reports').select('id,company_name,title,description,report_date,created_at').eq('status','approved').order('created_at',{ascending:false}).limit(100);if(q.query.q)r=r.ilike('company_name','%'+String(q.query.q).replace(/[%,]/g,'')+'%');const{data,error}=await r;if(error)throw error;s.json({disclaimer:'Unverified community reports, not confirmed findings.',reports:data})}));
app.post('/api/assistant',rateLimit({windowMs:60000,max:10}),w(async(q,s)=>{const t=String(q.body?.question||'').trim().slice(0,1000);if(!t)return bad(s,'Ask a question');s.json(await assistant(t))}));
if(process.argv[1].endsWith('server.js'))app.listen(PORT,()=>console.log('TrustHire API on '+PORT));
export default app;
